#!/bin/bash

echo "=== LLM Code Reviewer 使用例 ==="
echo ""

echo "例1: 基本的な使用方法（デフォルト設定）"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer"
echo ""

echo "例2: カスタムLLMサーバーとモデル"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer \\"
echo "  --api-url http://192.168.50.136:1234/v1 \\"
echo "  --model qwen/qwen3-coder-30b"
echo ""

echo "例3: セキュリティとパフォーマンスに焦点を当てたレビュー"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer \\"
echo "  --review-focus security \\"
echo "  --review-focus performance"
echo ""

echo "例4: PEP8チェックを含む包括的なレビュー"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer \\"
echo "  --review-focus pep8 \\"
echo "  --review-focus bugs \\"
echo "  --review-focus maintainability"
echo ""

echo "例5: カスタム除外パターン"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer \\"
echo "  --exclude \"*.pyc\" \\"
echo "  --exclude \"build/*\" \\"
echo "  --exclude \"install/*\" \\"
echo "  --exclude \"log/*\" \\"
echo "  --exclude \".svn/*\""
echo ""

echo "例6: カスタム出力場所"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer \\"
echo "  --output /code/custom-review.json"
echo ""

echo "例7: カスタムシステムプロンプト（コマンドライン）"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer \\"
echo "  --system-prompt \"あなたは20年の経験を持つシニアエンジニアです。厳格にレビューしてください。\""
echo ""

echo "例8: カスタムシステムプロンプト（ファイルから）"
echo "docker run -v \$(pwd)/my-ros2-project:/code \\"
echo "  -v \$(pwd)/prompt.txt:/prompt.txt \\"
echo "  llm-code-reviewer \\"
echo "  --prompt-file /prompt.txt"
echo ""

echo "例9: 英語でのレビュー"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer \\"
echo "  --language en"
echo ""

echo "例10: すべてのオプションを組み合わせた例"
echo "docker run -v \$(pwd)/my-ros2-project:/code llm-code-reviewer \\"
echo "  --api-url http://192.168.50.136:1234/v1 \\"
echo "  --model qwen/qwen3-coder-30b \\"
echo "  --context-length 262144 \\"
echo "  --review-focus security \\"
echo "  --review-focus performance \\"
echo "  --review-focus pep8 \\"
echo "  --review-focus ros2 \\"
echo "  --language ja \\"
echo "  --exclude \"*.pyc\" \\"
echo "  --exclude \"build/*\" \\"
echo "  --output /code/full-review.json"
echo ""
